name: Update Commands In Bulk
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 30 seconds to let deno deploy finish
        uses: jakejarvis/wait-action@master
        with:
          time: "30s"
      - uses: actions/checkout@v2
      - name: Trigger an request to set languages
        run: "curl --request POST --url ${{ secrets.DENO_DEPLOY_URL }}translations -H 'Authorization: ${{ secrets.REDEPLOY_AUTHORIZATION }}'"
      - name: Trigger an update request
        run: "curl --request POST --url ${{ secrets.DENO_DEPLOY_URL }}redeploy -H 'Authorization: ${{ secrets.REDEPLOY_AUTHORIZATION }}'"
